spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}  # 기본 프로필(default) 사용 (dev, prod 등 프로필 미설정 시)
  application:
    name: shopping-mall-api

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}        # 기본은 H2 인메모리 DB
    username: ${DB_USERNAME:sa}                    # 기본 sa
    password: ${DB_PASSWORD:}                       # 기본 비밀번호 없음
    driver-class-name: ${DB_DRIVER:org.h2.Driver}  # H2 드라이버

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}            # 배포시 create-drop 권장 (테이블 자동생성/삭제)
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}  # H2 Dialect
        format_sql: true
    defer-datasource-initialization: true

  # H2 콘솔 (개발 중에만 true 권장, 배포 시 false)
  h2:
    console:
      enabled: ${H2_CONSOLE:false}

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

server:
  port: ${PORT:8080}  # Railway가 할당해주는 포트 사용

jwt:
  secret: ${JWT_SECRET:Gd7#Lm@9$wKpZx!84MqRvT2nChEYBu1vXN5eF@zJL%UwDqRgHK!3Sn6tPjXxLa0Z}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:DEBUG}
    org.hibernate.type.descriptor.sql.BasicBinder: ${BINDER_LOG_LEVEL:TRACE}
    com.example.shoppingmall: ${APP_LOG_LEVEL:DEBUG}
