name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: |
        curl -sSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH

    - name: Login to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: railway login --apiToken $RAILWAY_TOKEN

    - name: Link Railway Project
      run: railway link --project ddf3b687-9d82-4ac5-843f-264d9c2f98f6  # 여기에 실제 프로젝트 ID 넣기

    - name: Deploy to Railway
      run: railway up --service shoppingmallbackendapi-production
