name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Railway
      uses: railwayapp/cli-action@v1
      with:
        railwayToken: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      run: railway up --service shopping-mall-backend
